name: mascotgirl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - blas
  - bleach
  - brotli
  - brotlipy
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - cryptography
  - cycler
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - flit-core
  - fonttools
  - freetype
  - icc_rt
  - icu
  - idna
  - importlib-metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab_pygments
  - jupyterlab_widgets
  - kiwisolver
  - libpng
  - libsodium
  - libtiff
  - libuv
  - libwebp
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - nest-asyncio
  - notebook
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - parso
  - pickleshare
  - pillow
  - pip
  - prometheus_client
  - prompt-toolkit
  - psutil
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - python=3.11
  - python-dateutil
  - python-fastjsonschema
  - python_abi
  - pytorch
  - pytorch-mutex
  - pywin32
  - pywinpty
  - pyzmq
  - qt
  - requests
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - soupsieve
  - sqlite
  - stack_data
  - terminado
  - tinycss2
  - tk
  - torchaudio
  - torchvision
  - tornado
  - traitlets
  - typing_extensions
  - urllib3
  - vc
  - vs2015_runtime
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - win_inet_pton
  - wincertstore
  - winpty
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pytorch-cuda=11.8
  - pip:
    - wxpython
    - openai==0.28.1
    - py7zr
    - opencv-python
    - rembg
    - fastapi
    - uvicorn
    - pyngrok
    - qrcode
    - cmudict
    - cn2an
    - faster-whisper==0.10.1
    - g2p_en
    - GPUtil
    - gradio==4.23.0
    - jieba
    - langid
    - librosa==0.9.2
    - loguru
    - matplotlib
    - num2words
    - numba
    - pyannote.audio>=3.1.0
    - pydantic>=2.0
    - pyloudnorm
    - pyopenjtalk-dict
    - pypinyin
    - pyworld-prebuilt
    - PyYAML
    - safetensors
    - tensorboard
    - transformers
    - umap-learn
    - langchain
    - accelerate
    - bitsandbytes
    - https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/releases/download/wheels/llama_cpp_python-0.2.36+cu118-cp311-cp311-win_amd64.whl